// <auto-generated />
using System;
using IncidentService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IncidentService.Migrations
{
    [DbContext(typeof(IncidentContext))]
    [Migration("20220405094041_NewMigration")]
    partial class NewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IncidentService.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("df2a59f1-e711-4a91-bccd-08188b54440b"),
                            CategoryName = "testName"
                        });
                });

            modelBuilder.Entity("IncidentService.Entities.Incident", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FurtherAction")
                        .HasColumnType("bit");

                    b.Property<string>("FurtherActionPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemSolved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Significance")
                        .HasColumnType("int");

                    b.Property<DateTime>("SolvingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ThirdPartyHelp")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Verifies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workspace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            IncidentId = new Guid("89fe62bb-18ed-4eba-8fcd-1b7dbfd20c38"),
                            ActionDescription = "test",
                            CategoryId = new Guid("df2a59f1-e711-4a91-bccd-08188b54440b"),
                            Date = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "test",
                            FurtherAction = true,
                            FurtherActionPerson = "test",
                            Number = "test01",
                            ProblemSolved = "test",
                            Remarks = "test",
                            Significance = 1,
                            SolvingDate = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThirdPartyHelp = true,
                            Time = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("8edc8128-dc5e-4202-ba18-0a623f954729"),
                            Verifies = "test",
                            Workspace = "test"
                        });
                });

            modelBuilder.Entity("IncidentService.Entities.Incident", b =>
                {
                    b.HasOne("IncidentService.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
